### ISSUE TITLE
"No names found, cannot describe anything"

### ISSUE THREAD

**Issue by wrm-git** [intel-go/rhoc#31]
From a fresh repo clone, the initial build reports this error multiple times before trying to build Rhoc:

wrmagro-MOBL wmagro/rhoc> make
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
Building Rhoc

**Comment by aregm** [comment]
Is it Windows, Linux or Mac?

**Comment by wrm-git** [comment]
Linux.

**Comment by wrm-git** [comment]
I just did "git clone". Not sure if that counts as shallow.

**Comment by anmyachev** [comment]
This [release](https://github.com/intel-go/rhoc/releases/tag/v0.1.0) solves the problem.
