### ISSUE TITLE
Successful build is missing hash value in resulting package name

### ISSUE THREAD

**Issue by wrm-git** [intel-go/rhoc#32]
At the end of a successful Rhoc build, the resulting package file name is package-linux-amd64-.tar.gz. Per the documentation, there should be a hash value after the dash and before the .tar.gz file extension.

**Comment by vnlitvinov** [comment]
Hello! Could you please clarify how did you acquire the source and how are you building it?

**Comment by wrm-git** [comment]
Just a git clone followed by a standard make.

**Comment by anmyachev** [comment]
This [release](https://github.com/intel-go/rhoc/releases/tag/v0.1.0) solves the problem.
